---
title: "I Preliminares"
subtitle: "Poner subtítulo"
author: "CruzJulian"
date: "`r Sys.Date()`"
output:
  tufte::tufte_html: default
  tufte::tufte_handout:
    citation_package: natbib
    latex_engine: xelatex
  tufte::tufte_book:
    citation_package: natbib
    latex_engine: xelatex
bibliography: bibliografia.bib
link-citations: yes
---

```{r setup, include=FALSE}
library("tufte")
# invalidate cache when the tufte version changes
knitr::opts_chunk$set(tidy = FALSE, cache.extra = packageVersion('tufte'))
options(htmltools.dir.version = FALSE)
```


El desarrollo teórico propuesto hace uso de algunos conceptos de teoría de la medida. Atendiendo a esto en el capítulo de preliminares se muestran los resultados en teoría de la medida que resultan relevantes para el desarrollo. Se espera que este resumen permita al lector situarse en los conceptos, el lenguaje y la notación usados más adelante.

# Conceptos básicos

## $\sigma$-álgebra

Dado un conjunto arbitrario, no vacío $\Omega$, una \textbf{$\sigma$-álgebra} $\mathcal{A}$ sobre $\Omega$ es un conjunto de subconjuntos de $\Omega$ que cumple tres condiciones:

```{marginfigure}
**Ejemplo: $\sigma$-álgebra de Borel.** La menor $\sigma$-álgebra sobre $\mathbb{R}$ que contiene todos los intervalos de la forma $(-\infty, a]$ con $a \in \mathbb{R}$ se llama **$\sigma$-álgebra de Borel** y se denota por $\mathcal{B}$. Además, la restricción de la $\sigma$-álgebra de Borel a los reales positivos se denomina **$\sigma$-álgebra de Borel en $\mathbb{R}^+$** y se denota por $\mathcal{B}^+$.

```

- $\Omega \in \mathcal{A}$.
- Si $A \in \mathcal{A}$ entonces su complemento $A' \in \mathcal{A}$. 
- Si $\{A_1, A_2, ... \} \subseteq \mathcal{A}$ entonces $\bigcup_{i = 1 }^\infty A_i$ es un elemento de $\mathcal{A}$.

El par $(\Omega, \mathcal{A})$ se llama un \textbf{Espacio medible} y los elementos de $\mathcal{A}$ se llaman \textbf{Conjuntos medibles}.

## Función medible

Sean $(\Omega, \mathcal{A})$ y $(\Omega', \mathcal{A}')$ espacios medibles. Sea una función $f: \Omega \rightarrow \Omega'$ . Entonces $f$ se llama **Función medible** si la preimagen de un conjunto medible es un conjunto medible. En símbolos, sea:

```{marginfigure}
**Ejemplo: Funciones Borel-medible.** Cuando $(\Omega', \mathcal{A}')$ corresponden a $(\mathbb{R}, \mathcal{B})$, se dice que $f$ es una **Función Borel-medible** si la preimagen de un conjunto Borel-medible es un conjunto medible.
```

$$f: \Omega \longrightarrow \Omega'$$

$$\omega \mapsto f(\omega)$$

$f$ es medible si 

$$D \in \mathcal{A}' \text{ implica que } f^{-1}(D) \in \mathcal{A}$$


## Teorema 1: (Ver demostración en el Apéndice 1)

Sean dos funciones $f: (\Omega, \mathcal{A}) \longrightarrow (\Omega', \mathcal{A}')$ y $g:(\Omega', \mathcal{A}') \longrightarrow (\Omega'', \mathcal{A}'')$. Si $f$ y $g$ son funciones medibles entonces $g\circ f$ es una función medible.

# Medida, espacio de medida

## Definición

Sea $(\Omega, \mathcal{A})$ un espacio medible. Una \textbf{Medida} en $(\Omega, \mathcal{A})$ es una función de conjuntos $\mu: \mathcal{A} \rightarrow [0, +\infty]$ que cumple:

- $\mu(\varnothing) = 0$
- Si dos conjuntos $A_1, A_2 \in \mathcal{A}$ son disyuntos, entonces $\mu(A_1 \cup A_2) = \mu(A_1) + \mu(A_2)$.

La terna $(\Omega, \mathcal{A}, \mu)$ se llama \textbf{Espacio de medida}.

## Definición

Sea $(\Omega, \mathcal{A})$ un espacio medible. El conjunto

$$\mathbb{P} := \{\mu: \mathcal{A}\rightarrow [0, +\infty] \mid \mu \text{ es una medida}\}$$

se llama **Conjunto de todas las medidas** sobre $(\Omega, \mathcal{A})$.

# Integral de Lebesgue

## Función indicatriz

Sea $(\Omega, \mathcal{A}, \mu)$ un espacio de medida. Sea $A$ un conjunto medible de $\Omega$. La **función indicatriz** de $A$ se define así:

$$I_A: \Omega \longrightarrow \{ 0 , 1\}$$

$$I_A(x) := 
\begin{cases}
1 \text{ si } x \in A\\
0 \text{ si } x \notin A
\end{cases}$$

## Integral de Lebesgue para funciones indicatrices

Sea $(\Omega, \mathcal{A}, \mu)$ un espacio de medida. Sean $A$ un conjunto medible e $I_A$ su función indicatriz. La **Integral de Lebesgue** de $I_A$ con respecto a $\mu$ se define como el valor de $\mu(A)$ y se nota así:

$$\int I_A d\mu := \mu(A)$$

## Integral de Lebesgue para funciones simples

Sea $(\Omega, \mathcal{A}, \mu)$ un espacio de medida. Sean: $\{A_i\}_{i\leq n}$ una colección conjuntos medibles disyuntos dos a dos, $\{a_i\}_{i\leq n}$ un conjunto de reales positivos y $f:=\sum_{i=1}^{n} a_i I_{A_i}$ una **función simple**. La **Integral de Lebesgue** de $f$ con respecto a $\mu$ corresponde al valor $\sum_{i=1}^{n} a_i \mu(A_i)$ y se nota así:

$$\int f d\mu := \sum_{i=1}^{n} a_i \mu(A_i)$$

## Integral de Lebesgue para funciones medibles positivas

Sea $(\Omega, \mathcal{A}, \mu)$ un espacio de medida. Sea $g$ una función real medible no negativa. La **Integral de Lebesgue** de $g$ con respecto a $\mu$ se define como

$$\int g d\mu := \sup\limits_{f\in F_g} \int f d\mu$$

Donde $F_g$ es el conjunto de todas las funciones simples $f$ que satisfacen $0\leq f(\omega) \leq g(\omega)$ para todo $\omega$ en $\Omega$.

## Integral de Lebesgue para funciones medibles

Sea $(\Omega, \mathcal{A}, \mu)$ un espacio de medida. Sea $g$ una función real medible, $g^{+}$ y $g^{-}$ sus partes positiva y negativa. La **Integral de Lebesgue** de $g$ con respecto a $\mu$ se define como

$$\int g d\mu := \int g^{+} d\mu - \int g^{-} d\mu$$

## Funcion integrable 

Sea $(\Omega, \mathcal{A}, \mu)$ un espacio de medida. Sea $g$ una función real medible, $g^{+}$ y $g^{-}$ sus partes positiva y negativa. Se dice que $g$ es **Integrable** con respecto a $\mu$ cuando las integrales con respecto a $\mu$ de sus partes positiva y negativa son finitas. [@GAR]

## Teorema 1 (Ver demostración en el Apéndice 1)

Sea $(\Omega, \mathcal{A})$ un espacio medible, $\{a_i\}_{i\leq n}$ una sucesión de números reales positivos y $\{\mu_i\}_{i\leq n}$ una sucesión de medidas sobre $(\Omega, \mathcal{A})$, $f$ una función real que es medible e integrable bajo cada $\mu_i$. La función de conjuntos $\mu = \sum_i a_i\mu_i$ es una medida en $(\Omega, \mathcal{A})$ y además se verifica que: 

$$\int f d\mu = \sum \limits_{i = 1}^n a_i \int f d\mu_i$$

# Derivada de Radon-Nikodyn

## Teorema1 (Ver demostración en el Apéndice 1)

Sea $\mu$ una medida en $\mathcal{A}$ y $h : \Omega \longrightarrow [0, \infty]$ una función medible. La función de conjuntos $\lambda: \mathcal{A} \longrightarrow [0, \infty]$ definida por $\lambda(A) := \int (I_A \cdot h) d\mu$ es una medida y además, si $f : \Omega \longrightarrow [0, \infty]$ es otra función medible se tiene que 

$$\int f d\lambda = \int (f \cdot h) d\mu$$

En el sentido de que si una de las integrales existe, la otra también y en ese caso coinciden.

## Definición

Sean $\mu$ y $\lambda$ medidas en $\mathcal{A}$ tales que existe $h : \Omega \longrightarrow [0, \infty]$ cumpliendo $\lambda(A) = \int_A h d\mu$ para todo $A \in \mathcal{A}$. Entonces $h$ se denomina **Derivada de Radon-Nikodyn** de $\lambda$ respecto a $\mu$ y se nota $\frac{d\lambda}{d\mu}$.

## Teorema 1 (Ver demostración en el Apéndice 1)

La derivada de Radon-Nikodyn de una suma finita de medidas es la suma finita de las derivadas. Sea $(\Omega, \mathcal{A})$ un espacio medible, $\{a_i\}_{i\leq n}$ una sucesión de números reales positivos y $\mu$ una medida sobre $(\Omega, \mathcal{A})$, $\{h_i\}_{i\leq n}$ una suceción de funciones reales medibles e integrables bajo $\mu$, además $\lambda_i = \int h_i d\mu$. Sea la función de conjuntos $\lambda = \sum_i a_i\lambda_i$. Entonces: 

$$\frac{d\lambda}{d\mu} = \sum\limits_{i=1}^{n} a_i h_i$$

# Probabilidad

## Espacio de probabilidad, Medida de probabilidad

Sea $(\Omega, \mathcal{A}, \mu)$ un espacio medible. Se denomina **Espacio de Probabilidad** si $\mu(\Omega)=1$. Asimismo $\mu$ se denomina **Medida de probabilidad** y en su notación se usa generalmente la letra $P$. 

## Variable aleatoria, Variable aleatoria real

Una función medible es una **Variable aleatoria** si su dominio es un espacio de probabilidad. Análogamente una funcion Borel-medible es una **Variable aleatoria real** si su dominio un espacio de probabilidad.

## Esperanza

En un espacio de probabilidad $(\Omega, \mathcal{A}, P)$ se denomina **Esperanza** de una variable aleatoria real $f$, y se denota $E(f)$ al valor de la integral de Lebesgue de $f$ con respecto a $P$ si es un valor real. En símbolos, si

$$\int f dP \in \mathbb{R}$$

entonces
$$E(f) := \int f dP$$

## Teorema 1 (Ver demostración en el Apéndice 1)

Sea un espacio de probabilidad $(\Omega, \mathcal{A}, P)$ y una variable aleatoria real $f$. En este caso $f$ es integrable si y sólo si su valor esperado $E(f)$ existe.

## Teorema 1 (Ver demostración en el Apéndice 1)

Sea $(\Omega, \mathcal{A})$ un espacio medible, $\{a_i\}_{i\leq n}$ una sucesión de números reales positivos cuya suma es 1 y $\{P_i\}_{i\leq n}$ una sucesión de medidas de probabilidad sobre $(\Omega, \mathcal{A})$, $f$ una función real medible e integrable bajo cada $P_i$. La función de conjuntos $P = \sum_i a_iP_i$ es una medida de probabilidad en $(\Omega, \mathcal{A})$ y además se verifica que: 
$$E(f) = \sum \limits_{i = 1}^n a_i \int f dP_i$$

## Densidad discreta

Dada una medida de probabilidad $P$ sobre los naturales se define la **Densidad de P**, $f$, como la derivada de Radon-Nicodyn de $P$ con respecto a la medida cardinal.

## Densidad continua

Dada una medida de probabilidad $P$ sobre los reales se define la **Densidad de P**, $f$, como la derivada de Radon-Nicodyn de $P$ con respecto a la medida de Lebesgue.

## Teorema 1 (Ver demostración en el Apéndice 1)

La densidad de una combinación convexa de medidas de probabilidad es la combinación convexa de las respectivas densidades.

